# SPDX-License-Identifier: GPL-2.0

sprd-camsys-objs := camsys.o capture.o config.o csi.o dcam.o lsc.o stats.o
sprd-camsys-objs += dcam-ums9230.o hw-ums9230.o

obj-$(CONFIG_VIDEO_SPRD_CAMSYS) += sprd-camsys.o
