# SPDX-License-Identifier: GPL-2.0
# Spreadtrum Audio Support

snd-soc-sprd-platform-y := sprd-pcm-dma.o sprd-pcm-compress.o
snd-soc-vbc-v4-dsp-y := vbc-v4-dsp.o

obj-$(CONFIG_SND_SOC_SPRD) += snd-soc-sprd-platform.o

obj-$(CONFIG_SND_SOC_SPRD_MCDT) += sprd-mcdt.o

obj-$(CONFIG_SND_SOC_SPRD_VBC_V4_DSP) += snd-soc-vbc-v4-dsp.o
